# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 237bdbcc5c1b54bd9ab564ea6b9343e9eae4edfb81ae26d4c8b1d2381147976e8aef9450a119f690b212413fbdc9253eed2e0ef88adbf4a496780605b3b8d01c

test:
  secret_key_base: 4673d2465187e353e28e7078b10acc0d11648e3d6f7a76692d5c13191a8d528efaafbffd621a4674a8f57cf743c5fc9ee950e470fa43bea77306349ff6083a93

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
